### PR TITLE
Upgrade avro to 1.9.0

### PR DESCRIPTION
**Pull request by mmadoo**
Upgrade Avro dependency to 1.9.0 (with [changelog](https://issues.apache.org/jira/browse/AVRO-2490?jql=project%20%3D%20AVRO%20AND%20fixVersion%20%3D%201.9.0))

### CODE REVIEW

**Comment by mmadoo** [comment]
The pipeline has failed as it requires oraclejdk8 which seems to be no more available. 
I do use travis, but using openjdk8 may fix this issue

**Comment by adamdubiel** [comment]
Thanks for the PR! Looks good, I will ask for a review :)

**Comment by mmadoo** [comment]
When does this PR will be merged ?

**Comment by druminski** [comment]
@mmadoo next week at the latest :) thanks for the PR

**Comment by cristaloleg** [comment]
New version 0.2.9 is released.

**Pull request closed without merging**
